name: pharmacy_plus
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: ^4.6.6
  mask_text_input_formatter: ^2.5.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  easy_localization: ^3.0.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/BALOOBHAIJAAN2-REGULAR.TTF
          weight: 400
        - asset: assets/fonts/BALOOBHAIJAAN2-MEDIUM.TTF
          weight: 500
        - asset: assets/fonts/BALOOBHAIJAAN2-SEMIBOLD.TTF
          weight: 600
        - asset: assets/fonts/BALOOBHAIJAAN2-BOLD.TTF
          weight: 700
        - asset: assets/fonts/BALOOBHAIJAAN2-EXTRABOLD.TTF
          weight: 800
  

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: images.dart
  field_prefix:

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icons/app_icon.png"
